### ISSUE TITLE
unit test is fail

### ISSUE THREAD

**Issue by manh-vv** [lecle/aloxide#79]
```log
@aloxide/bridge:  FAIL  test/ICONContractAdapter.test.ts (41.77 s)
@aloxide/bridge:   ● test ICON contract addapter › test generatePackage › should generatePackage successful
@aloxide/bridge:     expect(jest.fn()).toBeCalledTimes(expected)
@aloxide/bridge:     Expected number of calls: 1
@aloxide/bridge:     Received number of calls: 2
@aloxide/bridge:
@aloxide/bridge:       137 |
@aloxide/bridge:       138 |       adapter.generatePackage();
@aloxide/bridge:     > 139 |       expect(spyReadFileSync).toBeCalledTimes(1);
@aloxide/bridge:           |                               ^
@aloxide/bridge:       140 |       expect(spyReadFileSync).toBeCalledWith(
@aloxide/bridge:       141 |         path.resolve(templatePath, adapter.folderName, `${fileName}.hbs`),
@aloxide/bridge:       142 |         'utf-8',
@aloxide/bridge:
@aloxide/bridge:       at Object.<anonymous> (test/ICONContractAdapter.test.ts:139:31)
@aloxide/bridge:   ● test ICON contract addapter › test generateMainPy › should generateMainPy successful
@aloxide/bridge:     expect(jest.fn()).toBeCalledTimes(expected)
@aloxide/bridge:     Expected number of calls: 1
@aloxide/bridge:     Received number of calls: 4
@aloxide/bridge:
@aloxide/bridge:       167 |
@aloxide/bridge:       168 |       adapter.generateMainPy();
@aloxide/bridge:     > 169 |       expect(spyReadFileSync).toBeCalledTimes(1);
@aloxide/bridge:           |                               ^
@aloxide/bridge:       170 |       expect(spyReadFileSync).toBeCalledWith(
@aloxide/bridge:       171 |         path.resolve(templatePath, adapter.folderName, `${fileName}.hbs`),
@aloxide/bridge:       172 |         'utf-8',
@aloxide/bridge:
@aloxide/bridge:       at Object.<anonymous> (test/ICONContractAdapter.test.ts:169:31)
@aloxide/bridge:   ● test ICON contract addapter › test generateCallAPI › should generateCallAPI successful
@aloxide/bridge:     expect(jest.fn()).toBeCalledTimes(expected)
@aloxide/bridge:     Expected number of calls: 1
@aloxide/bridge:     Received number of calls: 5
@aloxide/bridge:
@aloxide/bridge:       222 |
@aloxide/bridge:       223 |       adapter.generateCallAPI();
@aloxide/bridge:     > 224 |       expect(spyReadFileSync).toBeCalledTimes(1);
@aloxide/bridge:           |                               ^
@aloxide/bridge:       225 |       expect(spyReadFileSync).toBeCalledWith(
@aloxide/bridge:       226 |         path.resolve(templatePath, adapter.folderName, `${fileName}.hbs`),
@aloxide/bridge:       227 |         'utf-8',
@aloxide/bridge:
@aloxide/bridge:       at Object.<anonymous> (test/ICONContractAdapter.test.ts:224:31)
@aloxide/bridge:   ● test ICON contract addapter › test generateTXAPI › should generateTXAPI successful
@aloxide/bridge:     expect(jest.fn()).toBeCalledTimes(expected)
@aloxide/bridge:     Expected number of calls: 1
@aloxide/bridge:     Received number of calls: 6
@aloxide/bridge:
@aloxide/bridge:       304 |
@aloxide/bridge:       305 |       adapter.generateTXAPI();
@aloxide/bridge:     > 306 |       expect(spyReadFileSync).toBeCalledTimes(1);
@aloxide/bridge:           |                               ^
@aloxide/bridge:       307 |       expect(spyReadFileSync).toBeCalledWith(
@aloxide/bridge:       308 |         path.resolve(templatePath, adapter.folderName, `${fileName}.hbs`),
@aloxide/bridge:       309 |         'utf-8',
@aloxide/bridge:
@aloxide/bridge:       at Object.<anonymous> (test/ICONContractAdapter.test.ts:306:31)
@aloxide/bridge:  PASS  test/ModelAdapter.test.ts (25.603 s)
@aloxide/bridge:   ● Console
@aloxide/bridge:     console.info
@aloxide/bridge:       ---- success generating file: bbModelBuilder.js
@aloxide/bridge:
@aloxide/bridge:       at FilePrinter.print (src/printer/FilePrinter.ts:33:17)
@aloxide/bridge: Test Suites: 1 failed, 6 passed, 7 total
@aloxide/bridge: Tests:       4 failed, 2 todo, 17 passed, 23 total
@aloxide/bridge: Snapshots:   0 total
@aloxide/bridge: Time:        57.433 s
@aloxide/bridge: Ran all test suites.
@aloxide/bridge: error Command failed with exit code 1.
```

**Comment by manh-vv** [comment]
@sanglt1902 Could you help check this?

**Comment by sanglt1902** [comment]
> @sanglt1902 Could you help check this?

Okay let me check

**Comment by sanglt1902** [comment]
Fixed
